# Generated by Django 3.1.4 on 2020-12-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_device_macaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='discovered',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='lastupdate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.CharField(default='Unkknown', max_length=64),
        ),
        migrations.AddField(
            model_name='device',
            name='osfamily',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='device',
            name='ostype',
            field=models.CharField(default='none', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='osvendor',
            field=models.CharField(default='none', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='ports',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='device',
            name='vendor',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='device',
            name='hostname',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='device',
            name='osname',
            field=models.CharField(max_length=32),
        ),
    ]
