# Generated by Django 3.1.4 on 2020-12-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20201216_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='macaddress',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='osfamily',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='osname',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='ostype',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='osvendor',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='ports',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='vendor',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
