# Generated by Django 3.1.4 on 2020-12-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20201216_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='lastresponded',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
