# Generated by Django 3.1.4 on 2020-12-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_device_lastresponded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='id',
        ),
        migrations.AlterField(
            model_name='device',
            name='hostip',
            field=models.GenericIPAddressField(primary_key=True, serialize=False),
        ),
    ]
