# Generated by Django 3.1.4 on 2020-12-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20201216_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='hostip',
            field=models.GenericIPAddressField(primary_key=True, serialize=False, unique=True),
        ),
    ]
