# Generated by Django 3.1.4 on 2020-12-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20201217_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ansible_group',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='dns_group',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
